working on running bamtagmultiome with customflag. error in iterator line 291: TypeError: digest() missing 1 required positional argument: 'reads', however, it is present.